abxy_mode: Switch
buttons:
  dual_joycons:
    A: A
    B: B
    C: null
    CAPT: null
    DOWN: DOWN
    HOME: GUIDE
    L: LB
    LEFT: LEFT
    L_STK: L_STK
    MINUS: BACK
    PLUS: START
    R: RB
    RIGHT: RIGHT
    R_STK: R_STK
    SL_L: SL_L
    SL_R: SL_R
    SR_L: SR_L
    SR_R: SR_R
    UP: UP
    X: X
    Y: Y
    ZL: LT
    ZR: RT
  procon:
    A: A
    B: B
    C: null
    CAPT: null
    DOWN: DOWN
    GL: null
    GR: Gyro Mouse
    HOME: GUIDE
    L: LB
    LEFT: LEFT
    L_STK: L_STK
    MINUS: BACK
    PLUS: START
    R: RB
    RIGHT: RIGHT
    R_STK: R_STK
    UP: UP
    X: X
    Y: Y
    ZL: LT
    ZR: RT
  single_joycon_l:
    CAPT: START
    DOWN: B
    L: LT
    LEFT: A
    L_STK: L_STK
    MINUS: BACK
    RIGHT: Y
    SL_L: LB
    SR_L: RB
    UP: X
    ZL: RT
  single_joycon_r:
    A: A
    B: X
    C: BACK
    HOME: GUIDE
    PLUS: START
    R: LT
    R_STK: L_STK
    SL_R: LB
    SR_R: RB
    X: B
    Y: Y
    ZR: RT
c_mapping: None
calibration_data:
  E0:EF:BF:81:06:9F:
  - 6.069767441860465
  - -14.046511627906977
  - -0.13953488372093023
  E0:EF:BF:EF:CC:BD:
  - 2.558139534883721
  - -10.914728682170542
  - 9.744186046511627
  E0:EF:BF:F0:0E:17:
  - -2.37984496124031
  - -0.4883720930232558
  - 2.751937984496124
combine_joycons: true
controller_mode: Xbox
deadzone: 50
gl_mapping: PSTPAD_L
gr_mapping: PSTPAD_R
gyro_activation_mode: Hold
gyro_bias_l:
- -2.37984496124031
- -0.4883720930232558
- 2.751937984496124
gyro_bias_r:
- 6.069767441860465
- -14.046511627906977
- -0.13953488372093023
gyro_mode: World
gyro_sensitivity: 4.0
mag_calibration_data:
  E0:EF:BF:81:06:9F:
  - 174.0
  - 155.0
  - 2.0
  E0:EF:BF:EF:CC:BD:
  - -239.5
  - 5.5
  - -474.0
  E0:EF:BF:F0:0E:17:
  - -0.5
  - -0.5
  - -0.5
mouse:
  buttons:
    left_joycon:
      left_button: L
      middle_button: L_STK
      right_button: ZL
    right_joycon:
      left_button: R
      middle_button: R_STK
      right_button: ZR
  enabled: true
  scroll_sensitivity: 2
  sensitivity: 5.0
open_when_startup: false
simulation_mode: PS4
slr_mapping: PSTPAD_R
srl_mapping: PSTPAD_L
start_minimized: false
stick_mouse_sensitivity: 5.0
stick_r_bias:
- 0.0
- 0.0
theme_mode: Dark
