abxy_mode: Switch
buttons:
  dual_joycons:
    A: A
    B: B
    C: null
    CAPT: null
    DOWN: DOWN
    HOME: GUIDE
    L: LB
    LEFT: LEFT
    L_STK: L_STK
    MINUS: BACK
    PLUS: START
    R: RB
    RIGHT: RIGHT
    R_STK: R_STK
    SL_L: SL_L
    SL_R: SL_R
    SR_L: SR_L
    SR_R: SR_R
    UP: UP
    X: X
    Y: Y
    ZL: LT
    ZR: RT
  procon:
    A: A
    B: B
    C: null
    CAPT: null
    DOWN: DOWN
    GL: null
    GR: Gyro Mouse
    HOME: GUIDE
    L: LB
    LEFT: LEFT
    L_STK: L_STK
    MINUS: BACK
    PLUS: START
    R: RB
    RIGHT: RIGHT
    R_STK: R_STK
    UP: UP
    X: X
    Y: Y
    ZL: LT
    ZR: RT
  single_joycon_l:
    CAPT: START
    DOWN: B
    L: LT
    LEFT: A
    L_STK: L_STK
    MINUS: BACK
    RIGHT: Y
    SL_L: LB
    SR_L: RB
    UP: X
    ZL: RT
  single_joycon_r:
    A: A
    B: X
    C: BACK
    HOME: GUIDE
    PLUS: START
    R: LT
    R_STK: L_STK
    SL_R: LB
    SR_R: RB
    X: B
    Y: Y
    ZR: RT
c_mapping: None
combine_joycons: true
controller_mode: Xbox
deadzone: 50
gl_mapping: PSTPAD_L
gr_mapping: PSTPAD_R
gyro_activation_mode: Hold
gyro_bias:
- 5.689655172413793
- -13.310344827586206
- -0.4482758620689655
gyro_mode: Yaw
gyro_sensitivity: 4.0
mouse:
  buttons:
    left_joycon:
      left_button: L
      middle_button: L_STK
      right_button: ZL
    right_joycon:
      left_button: R
      middle_button: R_STK
      right_button: ZR
  enabled: true
  scroll_sensitivity: 2
  sensitivity: 5.0
simulation_mode: PS4
slr_mapping: PSTPAD_R
srl_mapping: PSTPAD_L
stick_mouse_sensitivity: 5.0
stick_r_bias:
- 0.0
- 0.0
